### ISSUE TITLE
Edge hover or edge label feature not working 

### ISSUE THREAD

**Issue by ksmadhusudhan** [antman-oss/CentralityX#1]
Edge hover property mentioned in the document in not available in code , can you please tele me how can i fix the same

**Comment by antman-oss** [comment]
The issue here is the jsnetworkx library. In order to simply the code I switched to the jsnetworkx draw method to create the charts. Unfortunately there is a bug in the library which i was unable to investigate. I have followed the documenttion provided by jsnetworkx, however that functionality does not work advertised. I no longer support this extension, you would need to work through the bug in the jsnetworkx library
